### ISSUE TITLE
Vertically not aligned and Content box is smaller than the button

### ISSUE THREAD

**Issue by azaworld** [opencrvs/opencrvs-testland#235]
steps: 
1. log in as Sys National Admin
2. go to settings
3.click change 
4. see in mobile view
5. Go to change phone number
6. See Verify phone number

https://www.figma.com/file/RYc1inuUINR1PvEZq4dVjyWF/components?node-id=4380%3A3229

![Selection_006.png](https://images.zenhubusercontent.com/619f3ae43a0c92533cd6c6db/570abef8-7be5-4008-ac10-17dbbc858adb)![Selection_007.png](https://images.zenhubusercontent.com/619f3ae43a0c92533cd6c6db/7f0201b3-5919-4e5f-b53d-8a21f1f74b35)

**Comment by anny320** [comment]
issue resolved with form fix
